using System.Diagnostics;
using System.Text;
namespace MiniCompiladorFormularios;
enum Tipo { Formulario, Etiqueta, Campo, Boton, FinFormulario, Cadena, Identificador, FinArchivo }
record Token(Tipo Tipo,string Texto,int Linea);
record Elemento(string Tipo,string Valor);
static class Lenguaje
{
 public static List<Token> Lexico(string s){var r=new List<Token>();int i=0,l=1;while(i<s.Length){if(char.IsWhiteSpace(s[i])){if(s[i++]=='\n')l++;continue;}if(s[i]=='"'){int p=++i;while(i<s.Length&&s[i]!='"')i++;if(i==s.Length)throw new Exception("Error léxico: la cadena de texto no tiene comillas de cierre.");r.Add(new(Tipo.Cadena,s[p..i++],l));continue;}if(char.IsLetter(s[i])||s[i]=='_'){int p=i;while(i<s.Length&&(char.IsLetterOrDigit(s[i])||s[i]=='_'))i++;var x=s[p..i];r.Add(new(x switch{"FORMULARIO"=>Tipo.Formulario,"ETIQUETA"=>Tipo.Etiqueta,"CAMPO"=>Tipo.Campo,"BOTON"=>Tipo.Boton,"FIN_FORMULARIO"=>Tipo.FinFormulario,_=>Tipo.Identificador},x,l));continue;}throw new Exception($"Error léxico: '{s[i]}' no es un símbolo válido.");}r.Add(new(Tipo.FinArchivo,"",l));return r;}
 public static string Analizar(List<Token> t){int p=0;void E(Tipo x,string m){if(t[p].Tipo!=x)throw new Exception(m);p++;}E(Tipo.Formulario,"Error sintáctico: se esperaba FORMULARIO.");if(t[p].Tipo!=Tipo.Cadena)throw new Exception("Error sintáctico: FORMULARIO requiere un título.");var titulo=t[p++].Texto;var e=new List<Elemento>();var campos=new HashSet<string>();while(t[p].Tipo!=Tipo.FinFormulario){if(t[p].Tipo==Tipo.FinArchivo)throw new Exception("Error sintáctico: falta FIN_FORMULARIO.");var x=t[p++];if(x.Tipo==Tipo.Etiqueta){if(t[p].Tipo!=Tipo.Cadena)throw new Exception("Error sintáctico: ETIQUETA requiere un texto.");e.Add(new("Etiqueta",t[p++].Texto));}else if(x.Tipo==Tipo.Campo){if(t[p].Tipo!=Tipo.Identificador)throw new Exception("Error sintáctico: falta el identificador del campo.");var n=t[p++].Texto;if(!campos.Add(n))throw new Exception($"Error semántico: el campo '{n}' está repetido.");e.Add(new("Campo",n));}else if(x.Tipo==Tipo.Boton){if(t[p].Tipo!=Tipo.Cadena)throw new Exception("Error sintáctico: BOTON requiere un texto.");e.Add(new("Boton",t[p++].Texto));}else throw new Exception($"Error sintáctico: '{x.Texto}' no es un elemento válido.");}p++;E(Tipo.FinArchivo,"Error sintáctico: texto adicional no válido.");return Generar(titulo,e);}
 static string Generar(string titulo,List<Elemento> e){string Q(string x)=>x.Replace("\"","\\\"");var b=new StringBuilder();int y=25;b.AppendLine("using System;").AppendLine("using System.Windows.Forms;").AppendLine().AppendLine("internal static class Program").AppendLine("{").AppendLine("    [STAThread]").AppendLine("    static void Main()").AppendLine("    {").AppendLine("        ApplicationConfiguration.Initialize();").AppendLine().AppendLine("        var formulario = new Form").AppendLine("        {").AppendLine($"            Text = \"{Q(titulo)}\",").AppendLine("            Width = 420,").AppendLine("            Height = 180").AppendLine("        };").AppendLine();foreach(var x in e){var clase=x.Tipo=="Etiqueta"?"Label":x.Tipo=="Campo"?"TextBox":"Button";var prop=x.Tipo=="Campo"?"Name":"Text";b.AppendLine($"        formulario.Controls.Add(new {clase}").AppendLine("        {").AppendLine($"            {prop} = \"{Q(x.Valor)}\",").AppendLine("            Left = 25,").AppendLine($"            Top = {y},").AppendLine(x.Tipo=="Etiqueta"?"            AutoSize = true":"            Width = 300").AppendLine("        });").AppendLine();y+=x.Tipo=="Campo"?57:x.Tipo=="Boton"?63:25;}b.AppendLine($"        formulario.Height = Math.Max(180, {y+70});").AppendLine("        Application.Run(formulario);").AppendLine("    }").AppendLine("}");return b.ToString();}
}
static class Compilador { public static(string,bool,string) Ejecutar(string codigo){var d=Path.Combine(Path.GetTempPath(),"CompiladoresGrupo1","formulario-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"Program.cs"),codigo,Encoding.UTF8);File.WriteAllText(Path.Combine(d,"Formulario.csproj"),"<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms></PropertyGroup></Project>",Encoding.UTF8);var q=new ProcessStartInfo("dotnet","build Formulario.csproj -c Release"){WorkingDirectory=d,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8,UseShellExecute=false,CreateNoWindow=true};using var p=Process.Start(q)!;var o=p.StandardOutput.ReadToEnd()+p.StandardError.ReadToEnd();p.WaitForExit();return(p.ExitCode==0?"Compilación correcta.\r\n0 advertencias\r\n0 errores":o.Trim(),p.ExitCode==0,Path.Combine(d,"bin","Release","net8.0-windows","Formulario.exe"));}}
class Ventana:Form {readonly TextBox f=new(){Multiline=true,Dock=DockStyle.Fill,Font=new Font("Consolas",10),ScrollBars=ScrollBars.Both};readonly TextBox c=new(){Multiline=true,ReadOnly=true,Dock=DockStyle.Fill,Font=new Font("Consolas",9),ScrollBars=ScrollBars.Both};readonly TextBox r=new(){Multiline=true,ReadOnly=true,Dock=DockStyle.Fill};readonly DataGridView t=new(){ReadOnly=true,AllowUserToAddRows=false,Dock=DockStyle.Fill,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill};readonly Label e=new(){Dock=DockStyle.Fill};string? exe;public Ventana(){Text="Mini-compilador de lenguaje para formularios";Width=1100;Height=700;foreach(var x in new[]{"Tipo","Texto","Línea"})t.Columns.Add(x,x);var b=new FlowLayoutPanel{Dock=DockStyle.Top,Height=42};foreach(var x in new[]{("Cargar ejemplo",(Action)Ejemplo),("Analizar",(Action)(()=>Analizar())),("Generar formulario",Generar),("Abrir formulario generado",Abrir),("Limpiar",Limpiar)}){var z=new Button{Text=x.Item1,AutoSize=true};z.Click+=(_,_)=>x.Item2();b.Controls.Add(z);}var panel=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=3};panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));panel.RowStyles.Add(new RowStyle(SizeType.Percent,48));panel.RowStyles.Add(new RowStyle(SizeType.Percent,48));A(panel,f,"Código fuente\r\nFormato: FORMULARIO \"Título\" · ETIQUETA \"Texto\" · CAMPO identificador · BOTON \"Texto\" · FIN_FORMULARIO",0,0);A(panel,t,"Tokens",1,0);A(panel,c,"Código C# generado",0,1);A(panel,r,"Resultado",1,1);panel.Controls.Add(e,0,2);panel.SetColumnSpan(e,2);Controls.Add(panel);Controls.Add(b);Ejemplo();}void A(TableLayoutPanel p,Control x,string s,int a,int b){var q=new Panel{Dock=DockStyle.Fill};q.Controls.Add(x);q.Controls.Add(new Label{Text=s,Dock=DockStyle.Top,Height=s.Contains("Formato")?42:22});p.Controls.Add(q,a,b);}void Ejemplo(){f.Text="FORMULARIO \"Registro\"\r\nETIQUETA \"Nombre\"\r\nCAMPO nombre\r\nBOTON \"Guardar\"\r\nFIN_FORMULARIO";LimpiarSalida();}void Limpiar(){f.Clear();LimpiarSalida();}void LimpiarSalida(){t.Rows.Clear();c.Clear();r.Clear();exe=null;e.Text="Listo.";}bool Analizar(){try{var x=Lenguaje.Lexico(f.Text);t.Rows.Clear();foreach(var a in x)t.Rows.Add(a.Tipo,a.Texto,a.Linea);c.Text=Lenguaje.Analizar(x);r.Text="El formulario es válido.";e.Text="Análisis correcto.";return true;}catch(Exception x){r.Text=e.Text=x.Message;return false;}}void Generar(){if(!Analizar())return;var x=Compilador.Ejecutar(c.Text);r.Text=x.Item1;exe=x.Item2?x.Item3:null;e.Text=x.Item2?"Formulario generado y compilado correctamente.":"Error durante la compilación del formulario.";}void Abrir(){if(exe is null){e.Text="Primero genere un formulario válido.";return;}Process.Start(new ProcessStartInfo(exe){UseShellExecute=true});}}
static class Program{[STAThread]static void Main(){ApplicationConfiguration.Initialize();Application.Run(new Ventana());}}
